services:
  db:
    image: postgres:18
    volumes:
      - player-data:/var/lib/postgresql
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: chungus_db
    ports:
      - "5432:5432"

volumes:
  player-data:
